ex3 functions for problems 1(a)-(e)

In [260]:
import numpy as np

In [261]:
def kalman_1d(belief, sigma_v, sigma_w, u, z):
    x = belief[0]
    var = belief[1]

    # prediction
    x_pred = x + u
    var_pred = var + sigma_v

    # innovation
    nu = z - x_pred
    k = var_pred/(var_pred+sigma_w)

    # update
    x_new = x_pred + k*nu
    var_new = (1 - k) * var_pred

    posterior = [x_new, var_new]
    print(np.around(posterior,5))
    print()

    return posterior


In [262]:
sigma_v = 0.04
sigma_w = 0.01
U = [-0.5, 1.2, 0.3]
Z = [-0.7, 0.6, 0.95]
belief = [0, 1]

for i in range(3):
    belief = kalman_1d(belief, sigma_v, sigma_w, U[i], Z[i])


[-0.6981  0.0099]

[0.58362 0.00833]

[0.93862 0.00829]



In [263]:
def kalman_nd(belief, Sigma_v, Sigma_w, u, z):
    [r,c] = np.shape(belief)
    x = np.array(belief[:,0])
    var = belief[:,1:]

    # prediction
    x_pred = x + u
    var_pred = var + Sigma_v

    # innovation
    nu = z - x_pred
    K = var_pred*np.linalg.inv(var_pred+Sigma_w)

    # update
    x_new = x_pred + np.matmul(K,nu)
    var_new = np.matmul((np.identity(r) - K), var_pred)

    posterior = np.vstack((x_new, var_new))
    print(np.around(posterior.T,5))
    print()

    return posterior.T

In [264]:
sigma_v = np.array([[0.04, 0],
                    [0, 0.09]])

sigma_w = np.array([[0.01, 0],
                    [0, 0.02]])

U = np.array([[-0.5, 1.2, 0.3],
              [0.3, -0.6, 0.3]])

Z = np.array([[-0.7, 0.6, 0.95],
              [0.3, 0.0, 0.15]])

belief = np.array([[0, 1, 0],
                   [0, 0, 1]])

for i in range(3):
    belief = kalman_nd(belief, sigma_v, sigma_w, U[:,i], Z[:,i])


[[-0.6981   0.0099   0.     ]
 [ 0.3      0.       0.01964]]

[[ 0.58362  0.00833  0.     ]
 [-0.04628  0.       0.01691]]

[[0.93862 0.00829 0.     ]
 [0.16634 0.      0.01685]]



In [265]:
def kalman_1dmotion(belief, Sigma_v, Sigma_w, u, z):
    [r,c] = np.shape(belief)
    x = np.array(belief[:,0])
    var = belief[:,1:]

    # prediction
    x_pred = x + u
    var_pred = var + Sigma_v

    # innovation
    nu = z - x_pred
    K = var_pred*np.linalg.inv(var_pred+Sigma_w)

    # update
    x_new = x_pred + np.matmul(K,nu)
    var_new = np.matmul((np.identity(r) - K), var_pred)

    posterior = np.vstack((x_new, var_new))
    print(np.around(posterior.T,5))
    print()

    return posterior.T

In [266]:
sigma_v = np.array([0.03, 0.02])

sigma_w = 0.01

U = np.array([-0.2, 0.0, 0.1])

Z = np.array([0.4, 0.9, 0.8])

belief = np.array([[0, 1, 0],
                   [0.5, 0, 2]])

for i in range(3):
    belief = kalman_1dmotion(belief, sigma_v, sigma_w, U[:,i], Z[:,i])


[[-0.6981   0.0099   0.     ]
 [ 0.3      0.       0.01964]]

[[ 0.58362  0.00833  0.     ]
 [-0.04628  0.       0.01691]]

[[0.93862 0.00829 0.     ]
 [0.16634 0.      0.01685]]

